import { HumanMessage } from "@langchain/core/messages"
import {
  StateSchema,
  StateGraph,
  START,
  END,
  type GraphNode,
  type CompiledStateGraph,
} from "@langchain/langgraph"
import { z } from "zod"
import { cohereModel, mistralModel, geminiModel } from "./ai.service.js"
import { createAgent, providerStrategy } from "langchain"

// toolStrategy for other agents except gemini

const state = new StateSchema({
  problem_statement: z.string().default(""),
  solution_1: z.string().default(""),
  solution_2: z.string().default(""),
  judge_recommendation: z.object({
    solution_1_score: z.number().min(0).max(10),
    solution_2_score: z.number().min(0).max(10),
    solution_1_feedback: z.string().default(""),
    solution_2_feedback: z.string().default(""),
  }),
})

const solutionNode: GraphNode<typeof state> = async (state) => {
  const [mistralResponse, cohereResponse] = await Promise.all([
    mistralModel.invoke(state.problem_statement),
    cohereModel.invoke(state.problem_statement),
  ])

  return {
    solution_1: mistralResponse.text,
    solution_2: cohereResponse.text,
  }
}

const judgeNode: GraphNode<typeof state> = async (state, config) => {
  const { problem_statement, solution_1, solution_2 } = state

  const judgeAgent = createAgent({
    model: geminiModel,
    tools: [],
    responseFormat: providerStrategy(
      z.object({
        solution_1_score: z.number().min(0).max(10),
        solution_2_score: z.number().min(0).max(10),
        solution_1_feedback: z.string().default(""),
        solution_2_feedback: z.string().default(""),
      }),
    ),
    systemPrompt: `You are a judge tasked to evaluate two solutions generated by two differnt AI models. 
        Provide a score (0-10) and feedback for each solution along with reasoning why for scores. 
        Be fair and unbiased in your evaluation.`,
  })

  const judgeResponse = await judgeAgent.invoke({
    messages: [
      new HumanMessage(
        `Problem Statement: ${problem_statement}\n\n` +
          `Solution 1: ${solution_1}\n\n` +
          `Solution 2: ${solution_2}\n\n` +
          `Please evaluate both solutions and provide your scores and feedback.`,
      ),
    ],
  })

  const {
    solution_1_score,
    solution_2_score,
    solution_1_feedback,
    solution_2_feedback,
  } = judgeResponse.structuredResponse

  return {
    judge_recommendation: {
      solution_1_score,
      solution_2_score,
      solution_1_feedback,
      solution_2_feedback,
    },
  }
}

const graph = new StateGraph(state)
  .addNode("solution", solutionNode)
  .addNode("judge", judgeNode)
  .addEdge(START, "solution")
  .addEdge("solution", "judge")
  .addEdge("judge", END)
  .compile()

export default async function runGraph(problem_statement: string): Promise<any> {
  const result = await graph.invoke({
    problem_statement: problem_statement,
  })

  console.log("Graph Result:", result) // 👈 HERE

  return result
}
